version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WATCHPACK_POLLING=true
    ports:
      - "3100:3000"
    networks:
      - pluse-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  pluse-network:
    driver: bridge 